name: Sync devcontainer images

on:
  workflow_dispatch:
    inputs:
      manual:
        required: true
        description: "手动运行"
        default: "manual"

jobs:
  sync:
    strategy:
      fail-fast: false
      matrix:
        repo:
          - anaconda
          - base
          - cpp
          - dotnet
          - go
          - java
          - javascript-node
          - jekyll
          - miniconda
          - php
          - python
          - ruby
          - rust
          - typescript-node
          - universal
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: jaign
          password: ${{ secrets.ALIYUN_ACR_PASSWORD }}
      - name: Sync
        id: sync
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 360
          max_attempts: 10
          command: |
            podman run \
              -v ~/.docker/config.json:/auth.json:ro \
              docker://quay.io/skopeo/stable:latest sync \
              --all \
              --retry-times 10 \
              --authfile /auth.json \
              --src docker \
              --dest docker \
              mcr.microsoft.com/devcontainers/${{ matrix.repo }} \
              registry.cn-hangzhou.aliyuncs.com/mcr-devcontainers
      - name: Report
        run: |
          echo "Total attempts: ${{ steps.sync.outputs.total_attempts }}"
