name: "Sync Image (Filter: linux/amd64, linux/arm64)"

on:
  workflow_dispatch:
    inputs:
      runs_on:
        type: choice
        required: true
        description: "运行环境，默认 ubuntu-latest"
        default: "ubuntu-latest"
        options:
          - ubuntu-latest
          - windows-latest
          - macos-latest
          - self-hosted
      src_image:
        required: true
        description: "源镜像"
      des_tag:
        required: true
        description: "目标镜像名版本，完整镜像名: registry.cn-hangzhou.aliyuncs.com/jaign-mirror/default:[tag]"

jobs:
  sync:
    runs-on: ${{ inputs.runs_on }}
    steps:
      - name: Setup Crane
        uses: imjasonh/setup-crane@v0.1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: jaign
          password: ${{ secrets.ALIYUN_ACR_PASSWORD }}
      - name: Copy
        id: copy
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 360
          max_attempts: 10
          command: |
            crane index filter \
              --platform linux/amd64 \
              --platform linux/arm64 \
              ${{ inputs.src_image }} \
              --tag \
              registry.cn-hangzhou.aliyuncs.com/jaign-mirror/default:${{ inputs.des_tag }}
      - name: Report
        run: |
          echo "Image name: registry.cn-hangzhou.aliyuncs.com/jaign-mirror/default:${{ inputs.des_tag }}"
          echo "Total attempts: ${{ steps.copy.outputs.total_attempts }}"
